# Sample information - Add the accession ids of samples to be downloaded
samples:
  - "NZ_CP019041.1"
  - "NZ_CP091358.1"
  - "NZ_CP078045.1"
  - "NZ_CP048014.1"
  - "NZ_CP070518.1"
  - "NZ_CP027658.1"
  - "NZ_CP139270.1"
  
# Tool parameters
defensefinder:
  threads: 4

padloc:
  threads: 4

resfinder:
  threshold: 0.9
  coverage: 0.6

crisprcasfinder:
  installation_path: "resources/CRISPRCasFinder"

blast:
  evalue: 1e-6
  identity: 80

hmrg:
  evalue: "0.005"
  qcov_hsp_perc: "80"
